const fs = require('fs');

function getMetricValue(metricObj, key) {
    if (!metricObj) return 'N/A';
    if (metricObj.values && metricObj.values[key] !== undefined) {
        return metricObj.values[key];
    }
    if (metricObj[key] !== undefined) {
        return metricObj[key];
    }
    return 'N/A';
}

function formatValue(value, isRate = false) {
    if (value === 'N/A') return value;
    if (isRate) return (value * 100).toFixed(2) + '%';
    return Number(value).toFixed(2);
}

try {
    const summaryData = fs.readFileSync('summary.json', 'utf8');
    const summary = JSON.parse(summaryData);
    const metrics = summary.metrics;

    // Extract metrics defensively
    const totalRequests = getMetricValue(metrics.http_reqs, 'count');
    const throughput = getMetricValue(metrics.http_reqs, 'rate');
    
    const reqDuration = metrics.http_req_duration || {};
    const avgLatency = getMetricValue(reqDuration, 'avg');
    const minLatency = getMetricValue(reqDuration, 'min');
    const maxLatency = getMetricValue(reqDuration, 'max');
    const p95Latency = getMetricValue(reqDuration, 'p(95)');
    
    const failRate = getMetricValue(metrics.http_req_failed, 'rate');
    const checkRate = getMetricValue(metrics.checks, 'rate');

    const markdown = `
# 🏎️ ACE Technologies - API Load Testing Summary (k6)

**100 Virtual Users for 1 Minute**

| Metric | Value |
|--------|-------|
| **Total Requests** | ${totalRequests} |
| **Throughput (RPS)** | ${formatValue(throughput)} req/s |
| **Average Latency** | ${formatValue(avgLatency)} ms |
| **Min Latency** | ${formatValue(minLatency)} ms |
| **Max Latency** | ${formatValue(maxLatency)} ms |
| **P95 Latency** | ${formatValue(p95Latency)} ms |
| **Request Failure Rate** | ${formatValue(failRate, true)} |
| **Assertions Check Rate** | ${formatValue(checkRate, true)} |

*Generated by k6 Load Testing Pipeline*
`;

    const summaryFile = process.env.GITHUB_STEP_SUMMARY;
    if (summaryFile) {
        fs.appendFileSync(summaryFile, markdown);
        console.log('Appended k6 summary to GITHUB_STEP_SUMMARY.');
    } else {
        console.log('GITHUB_STEP_SUMMARY not set. Outputting to console:');
        console.log(markdown);
    }
} catch (error) {
    console.error('Error parsing k6 summary JSON:', error);
    process.exit(1); // Fail script if parsing fails
}
